reward: {approach_charger_1_doorway_1_lab : {at: ["hallway"], facing: ["nothing"]},
    approach_nothing_desk_1_hallway : {at: ["hallway"], facing: ["desk_1"]},
    approach_doorway_1_charger_1_lab: {at: ["lab"], facing: ["charger_1"]}}

continue_from: {approach_charger_1_doorway_1_lab : "approach_nothing_desk_1_hallway",
    approach_nothing_desk_1_hallway : "None",
    approach_doorway_1_charger_1_lab: "dock_charger_1_lab"}

failed_operator_name: "approach_charger_1_doorway_1_lab"

use_plan_flag: trie
plan_path:

load_model_flag: true
lfd_flag: false

model_path: "/home/mulip/catkin_ws/src/coffee-bot/coordinate_navigation/scripts/models"
data_path: "/home/mulip/catkin_ws/src/coffee-bot/coordinate_navigation/scripts/data"