object_list : ["doorway_1", "charger_1", "desk_1", "novel_object", "nothing"]

object_types : {
  room : ["lab", "hallway"],
  doorway: ["doorway_1"],
  charger: ["charger_1"],
  desk: ["desk_1"],
  nothing: ["nothing"]
}

objects : {
  lab: {},

  kitchen: {},

  doorway_1 : {connect : ["lab", "hallway"], inside: ["lab", "hallway"]},

  charger_1: {inside: ["lab"]},

  desk_1: {inside: ["hallway"]},

  nothing: {inside: ["lab", "hallway"]}
}

at_boundaries: {
  lab: [[0.156, 1.45], [-0.570, -0.005], [-1.796, 0.056], [-0.996, 2.036]],
  hallway: [[0.270, -0.697], [-0.332, -0.431], [0.465, 1.413], [1.095, 1.237]],
  none: [[-0.122, 0.145], [-0.357, 0.188], [-0.146, 0.757], [0.037, 0.666]]
}

facing_boundaries: {
  doorway_1__lab: {boundary: [[-0.287, 0.217], [-0.564, 0.281], [-0.162, 0.701], [-0.306, 0.762]], orientation: [ 0, 0, -0.507, 0.862], orientation_thresh: 0.524},
  doorway_1__hallway: {boundary: [[-0.124, 0.157], [0.027, 0.081], [0.190, 0.565], [-0.0278, 0.659]], orientation: [0, 0, 0.551, 0.835], orientation_thresh: 0.524}
}