waypoint_list: ["doorway_1_lab_lab", "doorway_1_lab_hallway", "doorway_1_hallway_hallway", "doorway_1_hallway_lab", "desk_1", "charger_1", "novel_object"]


waypoints: {
    doorway_1_lab_lab : [[-0.653, 0.652, 0], [ 0, 0, -0.170, 0.990]],
    doorway_1_lab_hallway : [[-0.568, 0.606, 0], [ 0, 0, 0.985, 0.175]],
    doorway_1_hallway_hallway : [[0.368, 0.242, 0], [ 0, 0, 0.986, 0.165]],
    doorway_1_hallway_lab : [[0.130, 0.313, 0], [ 0, 0, -0.201, 0.980]],
    desk_1 : [[0.537, 1.083, 0], [0, 0, 0.573, 0.819]],
    charger_1 : [[-0.466, 1.293, 0], [0, 0, 0.971, 0.238]],
    exploration_reset: [[-0.653, 0.652, 0], [ 0, 0, -0.170, 0.990]]
}