waypoint_list: ["doorway_1_lab_lab", "doorway_1_lab_hallway", "doorway_1_hallway_hallway", "doorway_1_hallway_lab", "desk_1", "charger_1", "novel_object"]


waypoints: {
    doorway_1_lab_lab : [[2.851, -2.340, 0], [ 0, 0, -0.416, 0.910]],
    doorway_1_lab_hallway : [[2.935, -2.198, 0], [ 0, 0, 0.861, 0.507]],
    doorway_1_hallway_hallway : [[4.003, -3.903, 0], [ 0, 0, 0.875, 0.483]],
    doorway_1_hallway_lab : [[4.085, -4.123, 0], [ 0, 0, -0.499, 0.867]],
    desk_1 : [[0.174, -5.906, 0], [0, 0, -0.517, 0.856]],
    charger_1 : [[-1.275, -3.492, 0], [ 0, 0, -0.973, 0.231]],
    novel_object : [[3.641, -3.086, 0], [0, 0, 0.866, 0.500]],
    exploration_reset: [[2.851, -2.340, 0], [ 0, 0, -0.416, 0.910]]
}