waypoint_list: ["doorway_1_lab_lab", "doorway_1_lab_hallway", "doorway_1_hallway_hallway", "doorway_1_hallway_lab", "desk_1", "charger_1"]


waypoints: {
    doorway_1_lab_lab : [[2.663, -1.776, 0], [ 0, 0, -0.307, 0.952]],
    doorway_1_lab_hallway : [[2.797, -1.931, 0], [ 0, 0, 0.868, 0.497]],
    doorway_1_hallway_hallway : [[4.206, -3.576, 0], [ 0, 0, 0.912, 0.411]],
    doorway_1_hallway_lab : [[4.300, -3.640, 0], [ 0, 0, -0.498, 0.867]],
    desk_1 : [[0.174, -5.906, 0], [0, 0, -0.517, 0.856]],
    charger_1 : [[-1.814, -2.631, 0], [ 0, 0, -0.975, 0.220]],
}