waypoint_list: ["doorway_1_lab_lab", "doorway_1_lab_hallway", "doorway_1_hallway_hallway", "doorway_1_hallway_lab", "desk_1", "charger_1"]


waypoints: {
    doorway_1_lab_lab : [[0.259, 0.301, 0], [ 0, 0, -0.891, 0.454]],
    doorway_1_lab_hallway : [[-0.137, -0.005, 0], [ 0, 0, 0.524, 0.851]],
    doorway_1_hallway_hallway : [[-0.595, -0.940, 0], [ 0, 0, 0.537, 0.844]],
    doorway_1_hallway_lab : [[-0.465, -0.719, 0], [ 0, 0, -0.849, -719]],
    desk_1 : [[0.174, -5.906, 0], [0, 0, -0.517, 0.856]],
    charger_1 : [[0.836, -0.331, 0], [ 0, 0, 0.509, 0.0.861]],
}