waypoint_list: ["doorway_1_lab_lab", "doorway_1_lab_hallway", "doorway_1_hallway_hallway", "doorway_1_hallway_lab", "desk_1", "charger_1"]


waypoints: {
    doorway_1_lab_lab : [[-0.740, 1.056, 0], [ 0, 0, -0.507, 0.862]],
    doorway_1_lab_hallway : [[0.211, 0.236, 0], [ 0, 0, 0.982, 0.189]],
    doorway_1_hallway_hallway : [[-0.334, 0.403, 0], [ 0, 0, 0.551, 0.835]],
    doorway_1_hallway_lab : [[-0.594, -0.493, 0], [ 0, 0, -0.120, 0.993]],
    desk_1 : [[0.772, 1.41, 0], [0, 0, -0.834, 0.551]],
    charger_1 : [[-1.258, 1.594, 0], [0, 0, -0.201, 0.978]]
}