agents: {
  turtlebot: {at: ["lab"], facing: ["charger_1"], docked: true}
}

object_types : {
  room : ["lab", "hallway"],
  doorway: ["doorway_1"],
  charger: ["charger_1"],
  desk: ["desk_1"],
  nothing: ["nothing"]
}

objects : {
  lab: {},

  kitchen: {},

  doorway_1 : {connect : ["lab", "hallway"], inside: ["lab", "hallway"]},

  charger_1: {inside: ["lab"]},

  desk_1: {inside: ["hallway"]},

  nothing: {inside: ["lab", "hallway"]}
}

at_boundaries: {
  lab: [[0.641, 4.607], [-3.04, 2.856], [-2.180, 0.736], [-4.198, -0.235], [-2.140, -5.529], [4.172, -2.309]],
  hallway: [[8.465, -1.139], [9.042, -2.213], [7.014, -3.466], [7.268, -3.869], [5.860, -4.750], [5.201, -4.226], [4.823, -4.321], [4.966, -5.168], [-0.346, -7.544], [-1.355, -5.470]]
}

facing_boundaries: {
  desk_1: {boundary: [[-0.005, -6.69, 0], [1.057, -6.339], [0.586, -5.352], [-0.398, -5.789]], orientation: [0, 0, -0.534, 0.846], orientation_thresh: 0.524},
  doorway_1__lab: {boundary: [[3.102, -3.133], [2.271, -2.192], [3.445, -1.512], [4.001, -2.627]], orientation: [0, 0, -0.422, 0.907], orientation_thresh: 0.524},
  doorway_1__hallway: {boundary: [[3.369, -3.478], [3.922, -4.303], [5.045, -3.819], [4.148, -2.696]], orientation: [0, 0, 0.907, 0.422], orientation_thresh: 0.524}
}