agents: {
  turtlebot: {at: ["lab"], facing: ["charger_1"], docked: true}
}

object_types : {
  room : ["lab", "hallway"],
  doorway: ["doorway_1"],
  charger: ["charger_1"],
  desk: ["desk_1"],
  nothing: ["nothing"]
}

objects : {
  lab: {},

  kitchen: {},

  doorway_1 : {connect : ["lab", "hallway"], inside: ["lab", "hallway"]},

  charger_1: {inside: ["lab"]},

  desk_1: {inside: ["hallway"]},

  nothing: {inside: ["lab", "hallway"]}
}

at_boundaries: {
  lab: [[0.641, 4.607], [-3.04, 2.856], [-2.180, 0.736], [-4.198, -0.235], [-2.140, -5.529], [4.172, -2.309]],
  hallway: [[8.465, -1.139], [9.042, -2.213], [7.014, -3.466], [7.268, -3.869], [5.860, -4.750], [5.201, -4.226], [4.823, -4.321], [4.966, -5.168], [-0.346, -7.544], [-1.355, -5.470]]
}

facing_boundaries: {
  desk_1: {boundary: [], orientation: 0.524},
  doorway_1__lab: {boundary: [], orientation: 0.524},
  doorway_1__hallway: {boundary: [], orientation: 0.524}
}