object_tags : {"1": {distance: 2, orientation: 0.524, predicates: {facing: "charger_1"}},
"5": {distance: 2, orientation: 0.524, predicates: {facing: "desk_1"}},
"9": {distance: 2, orientation: 2, predicates: {facing: "novel_object"}}
}