waypoint_list: ["doorway_1_lab_lab", "doorway_1_lab_hallway", "doorway_1_hallway_hallway", "doorway_1_hallway_lab", "desk_1", "charger_1", "novel_object"]


waypoints: {
    doorway_1_lab_lab : [[3.100, -2.340, 0], [ 0, 0, -0.437, 0.899]],
    doorway_1_lab_hallway : [[2.797, -1.931, 0], [ 0, 0, 0.868, 0.497]],
    doorway_1_hallway_hallway : [[4.206, -3.576, 0], [ 0, 0, 0.912, 0.411]],
    doorway_1_hallway_lab : [[4.300, -3.640, 0], [ 0, 0, -0.498, 0.867]],
    desk_1 : [[0.174, -5.906, 0], [0, 0, -0.517, 0.856]],
    charger_1 : [[-1.668, -3.570, 0], [ 0, 0, -0.975, 0.220]],
    novel_object : [[3.539, -4.148, 0], [0, 0, -0.967, 0.253]]
}